# Generated by Django 5.1.7 on 2025-04-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="preview_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="lesson_previews/"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
