# Generated by Django 5.1.7 on 2025-04-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_alter_lesson_preview_image_alter_lesson_video_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="preview_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="course_previews/"
            ),
        ),
    ]
