# Generated by Django 5.1.7 on 2025-04-18 08:53

from django.db import migrations, models

import materials.validators


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[materials.validators.validate_youtube_url],
            ),
        ),
    ]
