# Generated by Django 5.1.7 on 2025-04-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0006_alter_lesson_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
    ]
